export const COLOR_PALETTE = [
  // 기본 색상들
  [
    { color: "#000000", variant: "dark" },
    { color: "#434343", variant: "dark" },
    { color: "#666666", variant: "dark" },
    { color: "#999999", variant: "light" },
    { color: "#b7b7b7", variant: "light" },
    { color: "#cccccc", variant: "light" },
    { color: "#d9d9d9", variant: "light" },
    { color: "#efefef", variant: "light" },
    { color: "#f3f3f3", variant: "light" },
    { color: "#ffffff", variant: "light" },
  ],
  // 빨간색 계열
  [
    { color: "#980000", variant: "dark" },
    { color: "#ff0000", variant: "dark" },
    { color: "#ff9900", variant: "dark" },
    { color: "#ffff00", variant: "light" },
    { color: "#00ff00", variant: "light" },
    { color: "#00ffff", variant: "dark" },
    { color: "#4a86e8", variant: "dark" },
    { color: "#0000ff", variant: "dark" },
    { color: "#9900ff", variant: "dark" },
    { color: "#ff00ff", variant: "dark" },
  ],
  // 파스텔 톤
  [
    { color: "#e6b8af", variant: "light" },
    { color: "#f4cccc", variant: "light" },
    { color: "#fce5cd", variant: "light" },
    { color: "#fff2cc", variant: "light" },
    { color: "#d9ead3", variant: "light" },
    { color: "#d0e0e3", variant: "light" },
    { color: "#c9daf8", variant: "light" },
    { color: "#cfe2f3", variant: "light" },
    { color: "#d9d2e9", variant: "light" },
    { color: "#ead1dc", variant: "light" },
  ],
  // 진한 톤
  [
    { color: "#dd7e6b", variant: "light" },
    { color: "#ea9999", variant: "light" },
    { color: "#f9cb9c", variant: "light" },
    { color: "#ffe599", variant: "light" },
    { color: "#b6d7a8", variant: "light" },
    { color: "#a2c4c9", variant: "light" },
    { color: "#a4c2f4", variant: "light" },
    { color: "#9fc5e8", variant: "light" },
    { color: "#b4a7d6", variant: "light" },
    { color: "#d5a6bd", variant: "light" },
  ],
  // 매우 진한 톤
  [
    { color: "#cc4125", variant: "dark" },
    { color: "#e06666", variant: "dark" },
    { color: "#f6b26b", variant: "dark" },
    { color: "#ffd966", variant: "light" },
    { color: "#93c47d", variant: "dark" },
    { color: "#76a5af", variant: "dark" },
    { color: "#6d9eeb", variant: "dark" },
    { color: "#6fa8dc", variant: "dark" },
    { color: "#8e7cc3", variant: "dark" },
    { color: "#c27ba0", variant: "dark" },
  ],
  // 어두운 톤
  [
    { color: "#a61c00", variant: "dark" },
    { color: "#cc0000", variant: "dark" },
    { color: "#e69138", variant: "dark" },
    { color: "#f1c232", variant: "dark" },
    { color: "#6aa84f", variant: "dark" },
    { color: "#45818e", variant: "dark" },
    { color: "#3c78d8", variant: "dark" },
    { color: "#3d85c6", variant: "dark" },
    { color: "#674ea7", variant: "dark" },
    { color: "#a64d79", variant: "dark" },
  ],
];
